wandb_version: 1

depth:
  desc: null
  value: 6
iterations:
  desc: null
  value: 279
learning_rate:
  desc: null
  value: 0.03924060285884134
min_data_in_leaf:
  desc: null
  value: 49
rsm:
  desc: null
  value: 0.4923642172812275
subsample:
  desc: null
  value: 0.5998552449296723
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693595441.082147
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
