wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693506645.907492
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
learning_rate:
  desc: null
  value: 0.01
depth:
  desc: null
  value: 8
iterations:
  desc: null
  value: 200
