wandb_version: 1

depth:
  desc: null
  value: 5
iterations:
  desc: null
  value: 479
learning_rate:
  desc: null
  value: 0.056208812486275066
min_data_in_leaf:
  desc: null
  value: 57
rsm:
  desc: null
  value: 0.7878713605272796
subsample:
  desc: null
  value: 0.8719421976124276
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693592356.213732
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
