wandb_version: 1

depth:
  desc: null
  value: 9
iterations:
  desc: null
  value: 247
learning_rate:
  desc: null
  value: 0.045008790709042415
min_data_in_leaf:
  desc: null
  value: 22
rsm:
  desc: null
  value: 0.4373221544866741
subsample:
  desc: null
  value: 0.10481945387779124
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693597284.200825
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
