wandb_version: 1

depth:
  desc: null
  value: 3
iterations:
  desc: null
  value: 323
learning_rate:
  desc: null
  value: 0.0928525507975446
min_data_in_leaf:
  desc: null
  value: 55
rsm:
  desc: null
  value: 0.4407029852949843
subsample:
  desc: null
  value: 0.6529086771360684
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693594695.272453
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
