wandb_version: 1

depth:
  desc: null
  value: 5
iterations:
  desc: null
  value: 105
learning_rate:
  desc: null
  value: 0.04346803956071363
min_data_in_leaf:
  desc: null
  value: 41
rsm:
  desc: null
  value: 0.558648648574243
subsample:
  desc: null
  value: 0.2939217295886754
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693591954.421219
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
