wandb_version: 1

depth:
  desc: null
  value: 5
iterations:
  desc: null
  value: 303
learning_rate:
  desc: null
  value: 0.07293028446547162
min_data_in_leaf:
  desc: null
  value: 35
rsm:
  desc: null
  value: 0.6626821300572792
subsample:
  desc: null
  value: 0.8585372455163194
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693590001.373248
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
