wandb_version: 1

depth:
  desc: null
  value: 1
iterations:
  desc: null
  value: 456
learning_rate:
  desc: null
  value: 0.05465203512821295
min_data_in_leaf:
  desc: null
  value: 51
rsm:
  desc: null
  value: 0.6117867500198428
subsample:
  desc: null
  value: 0.9779667545430764
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693591753.729719
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
