wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693505702.026502
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
