wandb_version: 1

depth:
  desc: null
  value: 9
iterations:
  desc: null
  value: 303
learning_rate:
  desc: null
  value: 0.04744377980734135
min_data_in_leaf:
  desc: null
  value: 56
rsm:
  desc: null
  value: 0.7021187098911418
subsample:
  desc: null
  value: 0.43616456236631673
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693646901.642448
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 5
