wandb_version: 1

depth:
  desc: null
  value: 5
iterations:
  desc: null
  value: 301
learning_rate:
  desc: null
  value: 0.0856129222036732
min_data_in_leaf:
  desc: null
  value: 3
rsm:
  desc: null
  value: 0.7087197324743326
subsample:
  desc: null
  value: 0.7846687588625761
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.9
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693590619.469478
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.2
      5: 0.15.9
      8:
      - 1
      - 4
      - 5
